sudo: false
language: node_js
node_js:
- '0.12'
- '0.10'
- iojs
before_install:
- if [ "${TRAVIS_NODE_VERSION}" == "0.8" ]; then npm install -g npm@2.11.1; fi
script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install
- npm install bower
- bower install
- ls
#- gulp test
- gulp
after_script:
- chmod a+x ./scripts/deploy.sh
- chmod a+x ./scripts/derp.sh
- bash ./scripts/deploy.sh
matrix:
  fast_finish: true
notifications:
  irc:
    channels:
    - irc.freenode.org#unshift
    on_success: change
    on_failure: change
env:
  global:
    secure: hsD7rZdqEVp3CN/Ryu2vrRrr8t1Z7GKfnuhleCgsRdOzWzWMZdOZ28qZLZF2/8Rjc+iFHMuK4B5UHX8Rq25lDxX2/zc2LoJzNLhTPCiNhfNyzLvAoHnpt944sCV5JpP9x+bpUvjuF1cpD3AGG524clDmUd8UsAfcfipPf2/4x3E1+TXVmQ+f13P5/6AxVjhDO/0+sRJjvx6Aa50NPAD8KH0YSbf0NWydz6yNzAEQ8SGmXv5byEhm3mFNTPlgNoVwvbJM9OYsEhtNnQyls/uPsTjmKyhYx4G9PKFwn3BY2XyZHJXMpAZvex+qtjHoUlpKptahEPQUq4CYtm6rrB1/GodepAlArQrlRnLyZBLPKHRvFatQYCsj2aNyINV9+Az64a24zmZKwggFaSYj70TC5mMJeod65IMQpP+p0JfxS69qqlDh1U1Pkp4jIBjpEXG4Ufkd11qu5s1X89qqltnaN8sqim3Cyw8bmiIDnMUCucqP+6i9yo40nNZtqa/fHe9vI/R6q9vHmixfX5MZ1w41KRt1h4ukzlwl3zYaCzdNy1TMhiJ8umNw2UeYbLKS7hRzzCDBduPMgG6S4sfBWRqCtv9tRKRqyjSBhCJYyOtiE4ib/DE4zp5qnYmOtTjRuboPzJwut7n3XEmfrhws0MRsJ/WRlPQgqnVQhhghUbqSY18=
